name: test openresty

on: push
jobs:
  test-localhost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run build.sh
        run: ./buildOpenresty.sh
      - name: run init
        run: docker-compose --file openresty-docker-compose.yml up -d nginx

      - name: no token (10 per minute)
        run: ab -t 100 localhost:8080/verify

      - name: get JWT
        run: ./get_jwt.sh > ./jwt.txt
      - name: with token (1 per minute)
        run: ab -t 100 -H "Cookie: JWT=$(cat ./jwt.txt)" localhost:8080/verify

      - name: run stop
        run: docker-compose --file openresty-docker-compose.yml down
